/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui0;

import java.awt.Point;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author abdul
 * this class contains admins funtions
 */
public class Admin extends javax.swing.JFrame {
/*  con obj-> oject to iitlaize the connecting parameters in the makeConnection class
    */
    private makeConnection1 con;
    //admin data
    private String adminName;
    private String adminPass;
    private int adminId;
    //image path FOR ADD PRODUCT
    private String ImagepathAdd ;
    //image path FOR edit PRODUCT
    private String ImagepathEdit;
    private int quantity;
        
    public Admin() {
        initComponents();
        //to prevent the user(admin) to write on it.
        productsTextArea.setEditable(false);
         //center the program window in the middle of the screen
        this.setLocationRelativeTo(null);
        con = new makeConnection1();
        //get admins data from the login
        adminName = store.getLog().getUserNameOrEmail();
        adminPass = store.getLog().getPassword();
        adminId = store.getLog().getId();
        //to display the product details to provide admin with abstraction view of the products
        displaysProductList();
        //displays some admin's inforamtion
        adminNameLabel.setText(adminName);
        adminActivityHistoryPanel.setText(adminName+" Activity History");
        
        ImagepathAdd = "";
    }
    private Market marketObj = Market.getMarket(); 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        addProduct = new javax.swing.JButton();
        removeProduct = new javax.swing.JButton();
        editProduct = new javax.swing.JButton();
        set_product_describtion = new javax.swing.JTextField();
        setPriceTxtField = new javax.swing.JTextField();
        setNameTxtField = new javax.swing.JTextField();
        idProductToRemove = new javax.swing.JTextField();
        productIdToEdit = new javax.swing.JTextField();
        newProductPrice = new javax.swing.JTextField();
        newProductDescription = new javax.swing.JTextField();
        descriptionCheckBox = new javax.swing.JCheckBox();
        priceCheckBox = new javax.swing.JCheckBox();
        newProductName = new javax.swing.JTextField();
        nameCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        history = new javax.swing.JTextArea();
        imagecheckBox = new javax.swing.JCheckBox();
        imageChooser = new javax.swing.JButton();
        imageChooserEdit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productsTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        adminNameLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        logOutAdmin = new javax.swing.JButton();
        viewHistory = new javax.swing.JButton();
        adminActivityHistoryPanel = new javax.swing.JLabel();
        quantityInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newQuantity = new javax.swing.JTextField();
        quantityCheckBox = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(24, 20, 20));
        jPanel1.setToolTipText("");

        addProduct.setBackground(new java.awt.Color(0, 0, 0));
        addProduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setText("add product");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        removeProduct.setBackground(new java.awt.Color(0, 0, 0));
        removeProduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        removeProduct.setForeground(new java.awt.Color(255, 255, 255));
        removeProduct.setText("remove product");
        removeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductActionPerformed(evt);
            }
        });

        editProduct.setBackground(new java.awt.Color(0, 0, 0));
        editProduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        editProduct.setForeground(new java.awt.Color(255, 255, 255));
        editProduct.setText("edit product");
        editProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductActionPerformed(evt);
            }
        });

        set_product_describtion.setBackground(new java.awt.Color(0, 0, 0));
        set_product_describtion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        set_product_describtion.setForeground(new java.awt.Color(255, 255, 255));
        set_product_describtion.setText("add description");
        set_product_describtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_product_describtionActionPerformed(evt);
            }
        });

        setPriceTxtField.setBackground(new java.awt.Color(0, 0, 0));
        setPriceTxtField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        setPriceTxtField.setForeground(new java.awt.Color(255, 255, 255));
        setPriceTxtField.setText("set price");
        setPriceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPriceTxtFieldActionPerformed(evt);
            }
        });

        setNameTxtField.setBackground(new java.awt.Color(0, 0, 0));
        setNameTxtField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        setNameTxtField.setForeground(new java.awt.Color(255, 255, 255));
        setNameTxtField.setText("set name");
        setNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNameTxtFieldActionPerformed(evt);
            }
        });

        idProductToRemove.setBackground(new java.awt.Color(0, 0, 0));
        idProductToRemove.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idProductToRemove.setForeground(new java.awt.Color(255, 255, 255));
        idProductToRemove.setText("enter product id to remove");
        idProductToRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProductToRemoveActionPerformed(evt);
            }
        });

        productIdToEdit.setBackground(new java.awt.Color(0, 0, 0));
        productIdToEdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        productIdToEdit.setForeground(new java.awt.Color(255, 255, 255));
        productIdToEdit.setText("product id to edit");
        productIdToEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdToEditActionPerformed(evt);
            }
        });

        newProductPrice.setBackground(new java.awt.Color(0, 0, 0));
        newProductPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newProductPrice.setForeground(new java.awt.Color(255, 255, 255));
        newProductPrice.setText("0000");
        newProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductPriceActionPerformed(evt);
            }
        });

        newProductDescription.setBackground(new java.awt.Color(0, 0, 0));
        newProductDescription.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newProductDescription.setForeground(new java.awt.Color(255, 255, 255));
        newProductDescription.setText("new description");

        descriptionCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        descriptionCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        descriptionCheckBox.setText("description");
        descriptionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionCheckBoxActionPerformed(evt);
            }
        });

        priceCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        priceCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        priceCheckBox.setText("price");
        priceCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceCheckBoxActionPerformed(evt);
            }
        });

        newProductName.setBackground(new java.awt.Color(0, 0, 0));
        newProductName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newProductName.setForeground(new java.awt.Color(255, 255, 255));
        newProductName.setText("new name");

        nameCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        nameCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        nameCheckBox.setText("name");
        nameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCheckBoxActionPerformed(evt);
            }
        });

        history.setBackground(new java.awt.Color(33, 42, 50));
        history.setColumns(20);
        history.setForeground(new java.awt.Color(255, 255, 255));
        history.setRows(5);
        jScrollPane1.setViewportView(history);

        imagecheckBox.setBackground(new java.awt.Color(0, 0, 0));
        imagecheckBox.setForeground(new java.awt.Color(255, 255, 255));
        imagecheckBox.setText("image");
        imagecheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagecheckBoxActionPerformed(evt);
            }
        });

        imageChooser.setBackground(new java.awt.Color(0, 0, 0));
        imageChooser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        imageChooser.setForeground(new java.awt.Color(255, 255, 255));
        imageChooser.setText("choose image");
        imageChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageChooserActionPerformed(evt);
            }
        });

        imageChooserEdit.setBackground(new java.awt.Color(0, 0, 0));
        imageChooserEdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        imageChooserEdit.setForeground(new java.awt.Color(255, 255, 255));
        imageChooserEdit.setText("choose image");
        imageChooserEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageChooserEditActionPerformed(evt);
            }
        });

        productsTextArea.setBackground(new java.awt.Color(33, 42, 50));
        productsTextArea.setColumns(20);
        productsTextArea.setForeground(new java.awt.Color(255, 255, 255));
        productsTextArea.setRows(5);
        productsTextArea.setEnabled(false);
        jScrollPane2.setViewportView(productsTextArea);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Products");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(33, 42, 50));
        jPanel3.setForeground(new java.awt.Color(125, 125, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui0/pictures/icons8-male-user-100.png"))); // NOI18N

        userName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        adminNameLabel.setBackground(new java.awt.Color(80, 84, 92));
        adminNameLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminNameLabel.setText("name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(adminNameLabel)
                        .addGap(47, 47, 47))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back To Market");
        jButton1.setBorder(logOutAdmin.getBorder());
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        logOutAdmin.setBackground(new java.awt.Color(0, 0, 0));
        logOutAdmin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        logOutAdmin.setForeground(new java.awt.Color(255, 255, 255));
        logOutAdmin.setText("Log out");
        logOutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutAdminActionPerformed(evt);
            }
        });

        viewHistory.setBackground(new java.awt.Color(0, 0, 0));
        viewHistory.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        viewHistory.setForeground(new java.awt.Color(255, 255, 255));
        viewHistory.setText("view activity history");
        viewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logOutAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(viewHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOutAdmin)
                .addContainerGap(524, Short.MAX_VALUE))
        );

        adminActivityHistoryPanel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        adminActivityHistoryPanel.setForeground(new java.awt.Color(255, 255, 255));
        adminActivityHistoryPanel.setText("admin Activity History Panel");
        adminActivityHistoryPanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        quantityInput.setBackground(new java.awt.Color(0, 0, 0));
        quantityInput.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        quantityInput.setForeground(new java.awt.Color(255, 255, 255));
        quantityInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityInput.setText("quantity");
        quantityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityInputActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("description");

        jLabel4.setText("price");

        jLabel5.setText("quantity");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("name");

        newQuantity.setBackground(new java.awt.Color(0, 0, 0));
        newQuantity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newQuantity.setForeground(new java.awt.Color(255, 255, 255));
        newQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newQuantity.setText("quantity");
        newQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newQuantityActionPerformed(evt);
            }
        });

        quantityCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        quantityCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        quantityCheckBox.setText("quantity");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel6)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel5)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(setNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addGap(27, 27, 27)
                                                .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(newProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nameCheckBox))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(quantityCheckBox)
                                                        .addGap(0, 17, Short.MAX_VALUE))
                                                    .addComponent(newQuantity))
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(setPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(set_product_describtion, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(newProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(priceCheckBox))
                                                .addGap(18, 18, 18)
                                                .addComponent(newProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idProductToRemove)
                                        .addGap(93, 93, 93)
                                        .addComponent(descriptionCheckBox)
                                        .addGap(189, 189, 189)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(imageChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(71, 71, 71))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(imageChooserEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(productIdToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(editProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(removeProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                                        .addGap(43, 43, 43))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(imagecheckBox)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(adminActivityHistoryPanel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addProduct)
                            .addComponent(imageChooser)
                            .addComponent(set_product_describtion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(removeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(editProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productIdToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameCheckBox)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(priceCheckBox)
                                                .addComponent(quantityCheckBox)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(imagecheckBox)
                                            .addComponent(descriptionCheckBox))
                                        .addGap(9, 9, 9)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(imageChooserEdit)
                                    .addComponent(newProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(idProductToRemove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminActivityHistoryPanel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutAdminActionPerformed
        //hide admin
        setVisible(false);
        //terminate program
        System.exit(0);         //causes the Java virtual machine to exit, terminating the current process.
    }//GEN-LAST:event_logOutAdminActionPerformed
//open file explorer and allow to choose file to get it's path.
    public String getFilePath(){
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        try{
        return file.getPath();
        }
        catch(java.lang.NullPointerException e ){
            JOptionPane.showMessageDialog(null,"please select valid file");
        }
        //the default
        return "noAvailable.jpg";
    }
    // image chooser for Edit
    private void imageChooserEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageChooserEditActionPerformed
        ImagepathEdit = getFilePath();
    }//GEN-LAST:event_imageChooserEditActionPerformed

// image chooser for Add
    private void imageChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageChooserActionPerformed
            ImagepathAdd = getFilePath();
    }//GEN-LAST:event_imageChooserActionPerformed

    private void imagecheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagecheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagecheckBoxActionPerformed

    private void nameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameCheckBoxActionPerformed

    private void priceCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceCheckBoxActionPerformed

    }//GEN-LAST:event_priceCheckBoxActionPerformed

    private void descriptionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionCheckBoxActionPerformed

    private void newProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductPriceActionPerformed

    private void productIdToEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdToEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdToEditActionPerformed

    private void idProductToRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProductToRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProductToRemoveActionPerformed

    private void setNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setNameTxtFieldActionPerformed

    private void setPriceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPriceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setPriceTxtFieldActionPerformed

    private void set_product_describtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_product_describtionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set_product_describtionActionPerformed
    public void viewAdminsActivityHistory(){
        history.setText("");    //initially deleted to prevent duplication or worse
        ResultSet res = con.resFromDataBase("select product_name from products where admin_id = "+adminId);
        String productsByAdmins = "";
        boolean atleastone = false;

        try {
            while(res.next()){
                atleastone = true;
                productsByAdmins = productsByAdmins +" \n"+ res.getString("product_name");
            }
            history.setText(productsByAdmins);
        } catch (SQLException ex) {
            if(atleastone)  history.setText(productsByAdmins);
            else    JOptionPane.showMessageDialog(null,"admin has no activity history yet!");
        }
    }
    private void viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryActionPerformed
        viewAdminsActivityHistory();
    }//GEN-LAST:event_viewHistoryActionPerformed
    public void editProduct(String productId){
        
            Pattern p = Pattern.compile("^\\d+$");    //check it contains only numbers
            Matcher m = p.matcher(productId);
           
            if(!m.find())   {
                JOptionPane.showMessageDialog(null,"enter valid id");
                return;
            }
         
            String newName ;
            String newDescribtion ;
            double newPrice ;
            String newimagePath ;
            int quantity;

            try{
                ResultSet res = con.resFromDataBase("select * from products where product_id = "+productId);
                res.next();
                newName = res.getString("PRODUCT_NAME");
                quantity = Integer.parseInt(res.getString("quantity"));
                newPrice = Double.parseDouble(res.getString("PRODUCTS_PRICE"));
                newDescribtion = res.getString("PRODUCT_DESCRIPTION");
                newimagePath = res.getString("pictures");
                
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,"no such an id!");
                return;
            }
            
           
            /*checking if to consider the change in name or/and price or/and description */
            if(nameCheckBox.isSelected())   newName = newProductName.getText().trim();
                    
            if(quantityCheckBox.isSelected())   {
                try{
                    quantity = Integer.parseInt(newQuantity.getText());
                    if(quantity<=0) throw new NumberFormatException();
                }
                catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null,"quantity can only be positive number");
                    return;
                }
            }
            
            if(priceCheckBox.isSelected())  {
                try{
                    
                    newPrice = Double.parseDouble(newProductPrice.getText().trim());
                     if(newPrice<=0)  throw new NumberFormatException();
                  
                }
                 catch(NumberFormatException ex){
                         JOptionPane.showMessageDialog(null,"price must be positive!\nproduct hasn't been modified!");
                        return;
                }
            }
           
            if(descriptionCheckBox.isSelected())    newDescribtion = newProductDescription.getText().trim();
    
            if(imagecheckBox.isSelected())      {
                newimagePath = imageChooserEdit.getText();
                if(newimagePath.isEmpty())  newimagePath = "noAvailable.jpg";
            }

            
            con.performQuerey("UPDATE USERNAME.PRODUCTS SET PRODUCT_NAME ='"+newName+"', quantity = "+quantity+", PRODUCTS_PRICE = "+newPrice+", PRODUCT_DESCRIPTION ='"+newDescribtion+"', admin_id ="+adminId+", pictures = '"+newimagePath+"'  WHERE PRODUCT_ID ="+productId);
            
            JOptionPane.showMessageDialog(null,"product sucessfully modified");
    }
    private void editProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductActionPerformed
        try{
            String productId = productIdToEdit.getText().trim();
            editProduct(productId);
            
            displaysProductList();  //refresh
            viewAdminsActivityHistory(); //refresh
            marketObj.refreshProductPanel(); //reftesh
            //if there's/re error(s) in numbering formating for input print the error.
        }catch(NumberFormatException inputEx){
            JOptionPane.showMessageDialog(null,inputEx);
        }

    }//GEN-LAST:event_editProductActionPerformed
    public void removeProduct(String id){
        
            Pattern p = Pattern.compile("^\\d+$");    //check it contains only numbers
            Matcher m = p.matcher(id);
            if(!m.find())   {
                JOptionPane.showMessageDialog(null,"enter valid id");
                return;
            }
            int productId = Integer.parseInt(idProductToRemove.getText().trim());
            ResultSet res = con.resFromDataBase("select * from products where product_id ="+productId);
            try{
                if(!res.next()) throw new Exception();
                con.performQuerey("DELETE FROM USERNAME.PRODUCTS WHERE PRODUCT_ID ="+productId);
                JOptionPane.showMessageDialog(null,"product removed");
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,"enter valid id");
            }
           
            displaysProductList();  //refresh
            viewAdminsActivityHistory(); //refresh
            marketObj.refreshProductPanel(); //reftesh
    }
    private void removeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductActionPerformed
        try{
             
            String id = idProductToRemove.getText().trim();
            removeProduct(id);
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"enter valid id");
        }

    }//GEN-LAST:event_removeProductActionPerformed
    public void addProduct(String productName, String productDescribtion, double poductPrice , int quantity,  String imgPath){
        //check validity of input
        if(quantity<=0 || poductPrice<=0)  {
            if(poductPrice<=0 && quantity<=0 )  JOptionPane.showMessageDialog(null,"price and quantity can be only positive number");
            else if (poductPrice<=0)   JOptionPane.showMessageDialog(null,"price can be only positive number");
            else  JOptionPane.showMessageDialog(null,"quantity can be only positive number");
        }
        else{    
            //if the admin doesn'tprovid img then it's the default image
            
            if(ImagepathAdd.equals(""))    ImagepathAdd = "noAvailable.jpg";
            
            Product product = new Product(productName, poductPrice,quantity, productDescribtion, ImagepathAdd , adminId);
            ProductService productService = new ProductService(product);
            int res = productService.addProduct();

            if(res == 1)
                JOptionPane.showMessageDialog(null,"product added succesfuly");
            else JOptionPane.showMessageDialog(null,"error with adding product");
        }
    }
    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        //try and catch to avoid crashing in case of unsuitable input type
        try{
            //get products inforamtion from admin
            String productName = setNameTxtField.getText().trim();
            String productDescribtion = set_product_describtion.getText().trim();

            double poductPrice = Double.parseDouble(setPriceTxtField.getText().trim());
            quantity = Integer.parseInt(quantityInput.getText());
                addProduct(productName, productDescribtion, poductPrice, quantity, ImagepathAdd);
            
            
            displaysProductList();  //refresh product list in admin panel
            viewAdminsActivityHistory(); //refresh
            marketObj.refreshProductPanel(); //reftesh
        }
        catch(NumberFormatException inputEx){
            JOptionPane.showMessageDialog(null,"price and quantity can be only positive number");
        }
    }//GEN-LAST:event_addProductActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //hide admin
        setVisible(false);
        //set visible market
        marketObj.displayAllProducts();
        marketObj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        //doo nothing, it's a mistake
    }//GEN-LAST:event_jButton1MouseEntered

    private void quantityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityInputActionPerformed
        
    }//GEN-LAST:event_quantityInputActionPerformed

    private void newQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newQuantityActionPerformed
    
    public  void displaysProductList(){
        //initially et to blank
        productsTextArea.setText("");
        String result;
        int productsTextAreaWidth = productsTextArea.getWidth();
        //querey to get all products
        String querey = "SELECT * FROM PRODUCTS";
        ResultSet productRes = con.resFromDataBase(querey);
        final int ID_COLUMN_SIZE = 10;    final int NAME_COLUMN_SIZE = 20;  final int PRICE_COULMN_SIZE = 20; final int QUANTITY_COLUMN_SIZE = 5;
        String id;
        String name;
        String price ;
        String q;  //quantity
        try {
            while(productRes.next()){
                id = productRes.getString("product_id");
                name = productRes.getString("product_name");
                price = productRes.getString("products_price");
                price+="LE";
                q = productRes.getString("quantity");

                for(int i = id.length(); i<ID_COLUMN_SIZE; i++){
                    id += "-";
                }
                for(int i = name.length(); i<NAME_COLUMN_SIZE; i++){
                    name += "-";
                }
                for(int i = price.length(); i<PRICE_COULMN_SIZE; i++){
                    price += "-";
                }
                for(int i = q.length();  i<QUANTITY_COLUMN_SIZE; i++){
                    q += "-";
                }
                
            productsTextArea.append(id+name+price+q+"\n");
            }
       
        } catch (SQLException ex) {
            System.out.println("dnld");
        }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JLabel adminActivityHistoryPanel;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JCheckBox descriptionCheckBox;
    private javax.swing.JButton editProduct;
    private javax.swing.JTextArea history;
    private javax.swing.JTextField idProductToRemove;
    private javax.swing.JButton imageChooser;
    private javax.swing.JButton imageChooserEdit;
    private javax.swing.JCheckBox imagecheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutAdmin;
    private javax.swing.JCheckBox nameCheckBox;
    private javax.swing.JTextField newProductDescription;
    private javax.swing.JTextField newProductName;
    private javax.swing.JTextField newProductPrice;
    private javax.swing.JTextField newQuantity;
    private javax.swing.JCheckBox priceCheckBox;
    private javax.swing.JTextField productIdToEdit;
    private javax.swing.JTextArea productsTextArea;
    private javax.swing.JCheckBox quantityCheckBox;
    private javax.swing.JTextField quantityInput;
    private javax.swing.JButton removeProduct;
    private javax.swing.JTextField setNameTxtField;
    private javax.swing.JTextField setPriceTxtField;
    private javax.swing.JTextField set_product_describtion;
    private javax.swing.JLabel userName;
    private javax.swing.JButton viewHistory;
    // End of variables declaration//GEN-END:variables
}
/*
//get the last added product === MAX(id)
                     ResultSet res = con.resFromDataBase("SELECT *FROM products WHERE product_id = ( SELECT MAX(product_id) FROM products )");
                     //the cursor position start pointing before the first row of result to we make it point to the first row(and it's the only row in this query as id is unique)
                     res.next();
                     int productId = res.getInt("PRODUCT_ID");
                     //if we change update with insert command it will not work
                     con.performQuerey("UPDATE USERNAME.ADMIN SET PRODUCT_ID ="+productId);
                     //storing id of admins who did the changes:
                      con.performQuerey("UPDATE USERNAME.PRODUCTS SET admin_id ="+adminId+" WHERE PRODUCT_ID ="+productId);
                     */